services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8001
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./server:/app
    environment:
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:5173
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: